version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    # Build node project
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
      - run:
          name: List build files after build
          command: ls -alh dist public  # Check if the build output exists
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: |
            mkdir -p ~/artifacts
            ls -alh ~/artifacts  # Verify directory creation
      - run:
          name: Copy artifacts
          command: |
            cp -R dist public ~/artifacts 2>/dev/null || true
            ls -alh ~/artifacts  # Verify if files are copied correctly
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
      - persist_to_workspace:
          root: ~/artifacts  # Persist artifacts to workspace
          paths:
            - . # Make all contents under the home directory available to the next job

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run:
          name: Install SSH Client
          command: sudo apt-get update && sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - SHA256:4btujYU9LiUjTMFWqpGKYAAy2H3AB9SM0H9OCrvHyhc