version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    executor: node/default
    working_directory: /home/circleci/project  # Specify working directory
    steps:
      - checkout
      - node/install-packages:
          cache-path: /home/circleci/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
      - run:
          name: Create the artifacts directory if it doesn't exist
          command: |
            mkdir -p artifacts
            ls -alh artifacts  # Verify directory creation
      - run:
          name: Copy artifacts
          command: |
            cp -R dist public artifacts 2>/dev/null || true
            ls -alh artifacts  # Verify if files are copied correctly
      - persist_to_workspace:
          root: /home/circleci/project  # Persist from the specified working directory
          paths:
            - artifacts  # Persist the artifacts directory

  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: /home/circleci/deploy  # Specify working directory for deploy job
    steps:
      - setup_remote_docker
      - run:
          name: Install SSH Client
          command: sudo apt-get update && sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - SHA256:4btujYU9LiUjTMFWqpGKYAAy2H3AB9SM0H9OCrvHyhc
      - attach_workspace:
          at: /home/circleci/deploy  # Attach workspace to a custom path inside home directory
      - run:
          name: List workspace contents before deploy
          command: |
            echo "Listing contents of /home/circleci/deploy before deploy"
            ls -alh /home/circleci/deploy  # Verify the workspace is correctly attached and populated
      - run:
          name: List artifacts directory in workspace
          command: |
            echo "Listing artifacts directory inside workspace"
            ls -alh /home/circleci/deploy/artifacts  # Verify artifacts are available
      - run:
          name: Deploy to EC2
          command: |
            # SSH into EC2 instance and remove existing files
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-43-205-70-13.ap-south-1.compute.amazonaws.com "
              sudo rm -rf /var/www/html/*
              sudo mkdir -p /var/www/html
            "
            # Copy new build files to EC2
            scp -r /home/circleci/deploy/artifacts/* ubuntu@ec2-43-205-70-13.ap-south-1.compute.amazonaws.com:/var/www/html

workflows:
  build-and-deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node