version: 2.1

orbs:
  node: circleci/node@5.0.0  # Ensure the version is specified correctly

jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: |
            mkdir -p ~/artifacts
            ls -alh ~/artifacts  # Verify directory creation
      - run:
          name: Copy artifacts
          command: |
            cp -R dist public ~/artifacts 2>/dev/null || true
            ls -alh ~/artifacts  # Verify if files are copied correctly
      - persist_to_workspace:
          root: ~/artifacts  # Persist the artifacts folder to workspace
          paths:
            - .  # Persist everything under ~/artifacts

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker  # Ensure Docker is available if needed
      - run:
          name: Install SSH Client
          command: sudo apt-get update && sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - SHA256:4btujYU9LiUjTMFWqpGKYAAy2H3AB9SM0H9OCrvHyhc  # Ensure this matches your CircleCI SSH key fingerprint
      - attach_workspace:
          at: /workspace  # Attach workspace to /workspace directory in the deploy job
      - run:
          name: List workspace contents before deploy
          command: ls -alh /workspace  # Verify workspace is attached correctly
      - run:
          name: Deploy to EC2
          command: |
            # SSH into EC2 instance and remove existing files
            ssh -o StrictHostKeyChecking=no ubuntu@ec2-43-205-70-13.ap-south-1.compute.amazonaws.com "
              sudo rm -rf /var/www/html/*
              sudo mkdir -p /var/www/html
            "
            # Copy new build files to EC2
            scp -r /workspace/* ubuntu@ec2-43-205-70-13.ap-south-1.compute.amazonaws.com:/var/www/html

workflows:
  build-and-deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node